#!/usr/bin/env bash

# runs cordova-icon 

ASSETS='../src/assets/img/'
ICON='icon.png'
if [ ! -f $ICON ]; then
  echo -e "[1;31micon.png is missing.[0m\n\n Copying from shared/assets..."
  cp $ASSETS/$ICON .
fi

cordova-icon --icon=$ICON