#!/usr/bin/env bash

# runs cordova-splash 

ASSETS='../src/assets/img'

if [ ! -f splash.png ]; then
  echo -e "[1;31msplash.png is missing.[0m\n\n Copying from shared/assets..."
  cp $ASSETS/splash.png .
fi

cordova-splash