#!/usr/bin/env bash

if [ -z $ANDROID_HOME ]; then
  echo "ANDROID_HOME is not set, please be sure that it is defined and points to the Android SDK folder."
  exit 1
fi

zipalign=$(find $ANDROID_HOME -name zipalign)

if [ -z $zipalign ]; then
  echo "zipalign not found in your system.  Please make sure your Android SDK is installed properly."
  exit 1
fi
echo "Executing $zipalign"
echo ""
$zipalign "$@"